// main.m — entry point (ported from main.go).
//
// Runs the permission preflight behind a small attempt-cap guard, then hands
// the thread to NSApplication via gf_run (which blocks for the process'
// lifetime). main() is already on the OS main thread, so the Go version's
// runtime.LockOSThread() has no equivalent here.

#import <Foundation/Foundation.h>

#include "cocoa.h"
#include "hook_png.h"   // generated by the Makefile: hook_png[], hook_png_len

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// Permission-prompt guard. As a login item we launch once per login; if we
// can't pass the permission preflight we'd otherwise re-prompt on every login
// (or every manual relaunch) indefinitely. We give the preflight at most
// kAttemptsCap shots, with linear-ish backoff between launches (0s, 1s, 2s),
// then exit(0) and reset the counter so the next login starts fresh rather
// than spamming prompts. A successful run (past the preflight) resets it.
static const int kAttemptsCap = 3;

static NSString *attemptsFile(void) {
    return [NSString stringWithFormat:@"%@/Library/Application Support/go_fish/attempts.txt",
            NSHomeDirectory()];
}

static int readAttempts(void) {
    NSString *s = [NSString stringWithContentsOfFile:attemptsFile()
                                            encoding:NSUTF8StringEncoding
                                               error:NULL];
    if (!s) return 0;
    int n = [s integerValue] > 0 ? (int)[s integerValue] : 0;
    return n;
}

static void writeAttempts(int n) {
    NSString *path = attemptsFile();
    [[NSFileManager defaultManager] createDirectoryAtPath:[path stringByDeletingLastPathComponent]
                              withIntermediateDirectories:YES
                                               attributes:nil
                                                    error:NULL];
    [[NSString stringWithFormat:@"%d", n] writeToFile:path
                                           atomically:YES
                                             encoding:NSUTF8StringEncoding
                                                error:NULL];
}

int main(int argc, const char *argv[]) {
    @autoreleasepool {
        int attempts = readAttempts();
        if (attempts >= kAttemptsCap) {
            fprintf(stderr,
                "go_fish: gave up after %d permission attempts. Grant Accessibility\n",
                attempts);
            fprintf(stderr,
                "and Screen Recording in System Settings > Privacy & Security, then re-launch.\n");
            writeAttempts(0);
            return 0;
        }
        if (attempts > 0) {
            sleep((unsigned int)attempts);
        }

        if (!gf_hasAccessibility()) {
            fprintf(stderr, "go_fish needs Accessibility permission.\n");
            fprintf(stderr, "Grant it in System Settings > Privacy & Security > Accessibility, then re-run.\n");
            gf_promptAccessibility();
            writeAttempts(attempts + 1);
            return 1;
        }
        if (!gf_hasScreenRecording()) {
            fprintf(stderr, "go_fish needs Screen Recording permission for window thumbnails.\n");
            fprintf(stderr, "Grant it in System Settings > Privacy & Security > Screen Recording, then re-run.\n");
            gf_promptScreenRecording();
            writeAttempts(attempts + 1);
            return 1;
        }
        writeAttempts(0);

        fprintf(stderr, "go_fish running. Press Cmd+Tab to switch windows, or click the hook in the menu bar.\n");
        fprintf(stderr, "If the system switcher opens instead of go_fish, disable Cmd+Tab in\n");
        fprintf(stderr, "System Settings > Keyboard > Keyboard Shortcuts > Mission Control.\n");
        gf_run(hook_png, (int)hook_png_len); // blocks; NSApplication.run
    }
    return 0;
}
